ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'COLLABORATOR';

CREATE TYPE "Affiliation" AS ENUM ('BIG_TEN_NETWORK');
CREATE TYPE "CollaboratorProfile" AS ENUM ('BTN_STANDARD');
CREATE TYPE "ScheduleFollowSource" AS ENUM ('MANUAL', 'BOOKING');
