import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("onboarding dialog source wiring", () => {
  it("presents one shared invite and direct-create flow", () => {
    const source = readFileSync("src/components/onboarding/OnboardingDialog.tsx", "utf8");

    expect(source).toContain("Invite to register");
    expect(source).toContain("Create account");
    expect(source).toContain('fetch("/api/allowed-emails"');
    expect(source).toContain('url: "/api/users"');
    expect(source).toContain("Max 50 per batch");
    expect(source).toContain("already allowlisted or registered");
    expect(source).toContain("They will be asked to change it at first sign-in.");
    expect(source).toContain("Temporary passwords are only visible in this handoff step.");
    expect(source).toContain('className="border-[var(--green)]/40 bg-[var(--green-bg)]"');
    expect(source).not.toContain("border-green-200 bg-green-50");
    expect(source).toContain("Download temporary password CSV");
    expect(source).toContain("Bulk create");
    expect(source).toContain('fetch("/api/users/bulk-create"');
    expect(source).toContain("temporaryPasswordBulkCsv");
    expect(source).toContain("const ROLE_LABEL");
    expect(source).toContain("[user.name, user.email, ROLE_LABEL[user.role], temporaryPassword, \"yes\"]");
    expect(source).toContain("ROLE_LABEL[completion.user.role]");
    expect(source).toContain("ROLE_LABEL[bulkCreateRole]");
    expect(source).toContain("Temporary passwords will be generated by the server after submit.");
    expect(source).toContain("Reduce the batch to 50 ready accounts before creating.");
    expect(source).toContain("After creation, the profile opens so staff can finish details.");
    expect(source).toContain("<Alert>\n                <KeyRound className=\"size-4\" />");
    expect(source).toContain("Open profile");
  });

  it("previews bulk paste and CSV rows before saving invitations", () => {
    const source = readFileSync("src/components/onboarding/OnboardingDialog.tsx", "utf8");

    expect(source).toContain("previewInviteRows");
    expect(source).toContain("splitCsvLine");
    expect(source).toContain("Paste plain emails or CSV rows with `email, role`");
    expect(source).toContain("Fix these rows before saving.");
    expect(source).toContain("Duplicate in this paste");
    expect(source).toContain("Your role cannot invite this account role");
    expect(source).toContain("readyPreviewRows.map((row) => ({ email: row.email, role: row.role }))");
    expect(source).toContain('fetch("/api/allowed-emails/preview"');
    expect(source).toContain("Authenticated preview checks existing users and invitations before commit.");
    expect(source).toContain("Review account status before saving invitations.");
    expect(source).toContain("serverBlockingRows.length > 0");
    expect(source).toContain("Review the counts before closing or starting another batch.");
    expect(source).toContain("requested: emails.length");
  });

  it("names onboarding form controls for browser and accessibility tooling", () => {
    const source = readFileSync("src/components/onboarding/OnboardingDialog.tsx", "utf8");

    expect(source).toContain('name="bulkInvitationRows"');
    expect(source).toContain('name="bulkInvitationRole"');
    expect(source).toContain('name="singleInvitationEmail"');
    expect(source).toContain('autoComplete="email"');
    expect(source).toContain('name="singleInvitationRole"');
    expect(source).toContain('name="bulkCreateRows"');
    expect(source).toContain('name="bulkCreateRole"');
    expect(source).toContain('name="bulkCreateLocationId"');
  });

  it("opens the shared onboarding surface from Users and Allowed Emails", () => {
    const usersSource = readFileSync("src/app/(app)/users/page.tsx", "utf8");
    const allowedEmailsSource = readFileSync("src/app/(app)/settings/allowed-emails/page.tsx", "utf8");

    expect(usersSource).toContain("Onboard users");
    expect(usersSource).toContain("initialMode=\"invite\"");
    expect(usersSource).toContain("onInvitesChanged={() => reload()}");

    expect(allowedEmailsSource).toContain("OnboardingDialog");
    expect(allowedEmailsSource).toContain("Onboard users");
    expect(allowedEmailsSource).toContain('url: "/api/form-options"');
    expect(allowedEmailsSource).toContain('url: "/api/me"');
  });
});
