-- Convert scan_events.phase from text to the "ScanPhase" enum declared in
-- schema.prisma. The table predates the migration baseline and was created
-- with phase as plain text; enum-typed comparisons generated by Prisma
-- (phase = $1::"ScanPhase") fail with 42883 until the column is converted.
-- All existing values are valid enum labels (CHECKOUT, CHECKIN).
ALTER TABLE "scan_events" ALTER COLUMN "phase" TYPE "ScanPhase" USING ("phase"::"ScanPhase");
